// The pre-filing advance set-off check.
//
// ONE checker, called from THREE gates — GSTR-1 upload, GSTR-3B push, and
// Filing Status -> Filed. Three independently written checks drift, and a
// drifted gate is worse than none: it teaches staff the block is unreliable,
// and an unreliable block gets overridden by reflex.
//
// Read docs/ADVANCE_SETOFF_POSITIONS.md §5 before changing a severity or
// adding a rule. Builder clients are out of scope by construction (§1) —
// their Table 11 is generated by the builder engine and is balanced by
// construction, so a generic check over it produces only false blocks.

import { supabase } from '@/integrations/supabase/client';
import {
  buildAdvanceLedger, fetchAdvanceLedger, keyOf, parseKey, describeKey,
  zeroTax, addTax, subTax, totalTax, periodOrdinal, fpToMmYyyy, shortToMmYyyy,
  type AdvanceLedger, type TaxAmount,
} from './advanceBalance';
import {
  fetchRegister, registerClosingByKey, reconcileRegister, receiptKey, planRefundOffsets,
} from './advanceRegister';
import { resolveSchemeForPeriod } from '@/utils/schemeResolver';
import { isQuarterEndMonth } from '@/types';

/**
 * Rupee value below which a difference is treated as rounding noise.
 *
 * This number protects the CREDIBILITY of the hard block, which is the only
 * thing that makes it work. A gate that fires on three rupees becomes a reflex
 * click within a week, and a reflex click is indistinguishable from no gate.
 * Not yet exposed in Settings — see §10 of the doc for why.
 */
export const ADVANCE_MATERIALITY_DEFAULT = 1000;

/** Proportional guard, applied together with the rupee threshold on rule 2. */
const SHORTFALL_PCT_TRIGGER = 0.10;

/** Months after which an unadjusted advance is worth a second look. */
const STALE_ADVANCE_MONTHS = 6;

export type AdvanceFindingCode =
  | 'NO_SETOFF_REPORTED'      // rule 1
  | 'SETOFF_SHORT'            // rule 2
  | 'OVER_ADJUSTED'           // rule 3
  | 'AMENDMENT_UNRECONCILED'  // rule 4
  | 'OPEN_NO_INVOICE'         // rule 5
  | 'STALE_ADVANCE'           // rule 6
  | 'RECEIPT_NOT_IN_REGISTER' // rule 7 — register-backed clients only
  | 'REGISTER_DIVERGED'       // rule 8 — register-backed clients only
  | 'REFUND_NEEDS_11A_OFFSET';// rule 9 — register-backed clients only

export type AdvanceSeverity = 'hard' | 'soft';

export interface AdvanceFinding {
  code: AdvanceFindingCode;
  severity: AdvanceSeverity;
  /** Advance key this concerns, where the finding is key-scoped. */
  key?: string;
  keyLabel?: string;
  title: string;
  detail: string;
  /** Populated on rules 1-3, so the dialog can offer to write the 11B row. */
  suggested?: {
    /** Taxable advance value to report in Table 11B for this key. */
    taxable: number;
    ratePct: number;
    pos: string;
    splyTy: string;
    tax: TaxAmount;
  };
  amountAtRisk?: number;
}

export interface AdvanceCheckResult {
  /** 'hard' if any finding is hard; 'soft' if only soft; 'ok' if none. */
  severity: 'ok' | 'soft' | 'hard';
  findings: AdvanceFinding[];
  /**
   * Stable hash of the hard findings. An approved override is bound to this;
   * if the draft changes, the fingerprint changes and the override lapses.
   */
  fingerprint: string;
  /** Null when the check did not run (builder client, no data, error). */
  ledger: AdvanceLedger | null;
  /** Set when the check deliberately did not run, with the reason. */
  skipped?: string;
  openTotal: TaxAmount;
}

const num = (v: unknown): number => {
  const n = typeof v === 'number' ? v : parseFloat(String(v ?? ''));
  return Number.isFinite(n) ? n : 0;
};

const inr = (n: number): string =>
  `₹${(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const prevPeriod = (mmYyyy: string): string => {
  const [mm, yyyy] = (mmYyyy || '').split('/');
  const m = Number(mm), y = Number(yyyy);
  if (!m || !y) return '';
  return m === 1 ? `12/${y - 1}` : `${String(m - 1).padStart(2, '0')}/${y}`;
};

/**
 * Taxable value of this draft's outward invoices, keyed the same way advances
 * are (POS + rate + supply type). Credit/debit notes are excluded: a note is
 * not an invoice that can absorb an advance. Exports are excluded too — an
 * advance against an export is not reported through Table 11A in this app's
 * clients' returns, and including them would fire rule 1 on zero-rated value.
 */
function invoiceTaxableByKey(json: any, homeState: string): Map<string, number> { // eslint-disable-line @typescript-eslint/no-explicit-any
  const out = new Map<string, number>();
  const bump = (pos: string, ratePct: number, txval: number) => {
    if (!pos || !txval) return;
    const splyTy = pos === homeState ? 'INTRA' : 'INTER';
    const k = keyOf({ pos, ratePct, splyTy });
    out.set(k, (out.get(k) || 0) + txval);
  };
  const j = json || {};
  (j.b2b || []).forEach((party: any) => (party.inv || []).forEach((inv: any) => // eslint-disable-line @typescript-eslint/no-explicit-any
    (inv.itms || []).forEach((it: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
      const d = it?.itm_det || it || {};
      bump(String(inv.pos || ''), num(d.rt), num(d.txval));
    })));
  (j.b2cl || []).forEach((state: any) => (state.inv || []).forEach((inv: any) => // eslint-disable-line @typescript-eslint/no-explicit-any
    (inv.itms || []).forEach((it: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
      const d = it?.itm_det || it || {};
      bump(String(state.pos || ''), num(d.rt), num(d.txval));
    })));
  (j.b2cs || []).forEach((r: any) => bump(String(r.pos || ''), num(r.rt), num(r.txval))); // eslint-disable-line @typescript-eslint/no-explicit-any
  return out;
}

/** Advance groups of one section, summed per key. Mirrors advanceBalance. */
function advanceByKey(groups: any[], homeState: string): Map<string, TaxAmount> { // eslint-disable-line @typescript-eslint/no-explicit-any
  const out = new Map<string, TaxAmount>();
  (groups || []).forEach((g: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
    const declared = String(g?.sply_ty || '').toUpperCase();
    const pos = String(g?.pos || '');
    const splyTy = declared === 'INTRA' || declared === 'INTER'
      ? declared
      : (pos && pos === homeState ? 'INTRA' : 'INTER');
    const itms = Array.isArray(g?.itms) && g.itms.length ? g.itms : [g];
    itms.forEach((it: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
      const k = keyOf({ pos, ratePct: num(it?.rt), splyTy });
      out.set(k, addTax(out.get(k) || zeroTax(), {
        taxable: num(it?.ad_amt), igst: num(it?.iamt), cgst: num(it?.camt), sgst: num(it?.samt), cess: num(it?.csamt),
      }));
    });
  });
  return out;
}

/** Tax on a taxable amount at a rate, split by supply type. */
const taxFor = (taxable: number, ratePct: number, splyTy: string): TaxAmount => {
  const r2 = (n: number) => Math.round(n * 100) / 100;
  if (splyTy === 'INTRA') {
    const half = r2((ratePct / 200) * taxable);
    return { taxable, igst: 0, cgst: half, sgst: half, cess: 0 };
  }
  return { taxable, igst: r2((ratePct / 100) * taxable), cgst: 0, sgst: 0, cess: 0 };
};

/** Order-independent, stable hash of the hard findings. */
function fingerprintOf(findings: AdvanceFinding[]): string {
  const material = findings
    .filter((f) => f.severity === 'hard')
    .map((f) => `${f.code}|${f.key || ''}|${Math.round(f.amountAtRisk || 0)}`)
    .sort()
    .join(';');
  if (!material) return '';
  let h = 5381;
  for (let i = 0; i < material.length; i += 1) h = ((h * 33) ^ material.charCodeAt(i)) >>> 0;
  return h.toString(16).padStart(8, '0');
}

export interface AdvanceCheckInput {
  clientId: string;
  gstin: string;
  /** MM/YYYY — the return period being filed. */
  periodMonth: string;
  /** The JSON about to be filed. Pass the draft, not the stored row. */
  draftJson: any; // eslint-disable-line @typescript-eslint/no-explicit-any
  /** clients.regular_sub_type — 'Builder' short-circuits the whole check. */
  regularSubType?: string | null;
  /**
   * clients.registration_type. Used to spot a QRMP client filing an OPTIONAL
   * IFF month, where a hard block would be definitionally wrong — see below.
   */
  registrationType?: string | null;
  materialityThreshold?: number;
}

/**
 * Under QRMP the invoices for months 1 and 2 of a quarter go out in the IFF,
 * but Table 11B lives only in the quarter-end GSTR-1. So an advance genuinely
 * cannot be set off in an optional IFF month, and a hard block there would fire
 * on a return that is correct as filed.
 *
 * Findings are still RAISED — staff should see the advance coming — but every
 * one is downgraded to advisory. The full gate stands at the quarterly GSTR-1
 * and GSTR-3B (Q), which is where Table 11B actually is.
 */
async function isOptionalIffPeriod(
  clientId: string,
  periodMonth: string,
  registrationType?: string | null,
): Promise<boolean> {
  if (!registrationType) return false;
  try {
    const scheme = await resolveSchemeForPeriod(clientId, periodMonth, registrationType as never);
    if (String(scheme) !== 'IFF') return false;
    const month = Number((periodMonth || '').split('/')[0]);
    return !!month && !isQuarterEndMonth(month);
  } catch {
    // Unknown scheme must not silently relax the gate — fail towards the
    // stricter behaviour, which is the full check.
    return false;
  }
}

export async function runAdvanceSetoffCheck(input: AdvanceCheckInput): Promise<AdvanceCheckResult> {
  const threshold = input.materialityThreshold ?? ADVANCE_MATERIALITY_DEFAULT;
  const empty: AdvanceCheckResult = {
    severity: 'ok', findings: [], fingerprint: '', ledger: null, openTotal: zeroTax(),
  };

  // §1 — builders are excluded in code, not by convention.
  if (String(input.regularSubType || '').trim() === 'Builder') {
    return { ...empty, skipped: 'Builder client — advances are managed by the Builder module.' };
  }
  if (!input.clientId || !input.periodMonth) {
    return { ...empty, skipped: 'No client or period selected.' };
  }

  const homeState = (input.gstin || '').slice(0, 2);
  const draft = input.draftJson || {};

  // Ledger INCLUDING this draft, so an amendment sitting in the draft that
  // restates an earlier month is reflected in the balance it is checked against.
  const ledger = await fetchAdvanceLedger({
    clientId: input.clientId,
    gstin: input.gstin,
    upto: input.periodMonth,
    draftOverride: { period: input.periodMonth, json: draft },
  });

  const draftAt = advanceByKey(draft.at, homeState);
  const draftTxpd = advanceByKey(draft.txpd, homeState);
  const invoices = invoiceTaxableByKey(draft, homeState);

  // Balance available for adjustment this month = closing after the draft,
  // with this month's own 11B added back.
  const available = new Map<string, TaxAmount>();
  ledger.closingByKey.forEach((v, k) => available.set(k, v));
  draftTxpd.forEach((v, k) => available.set(k, addTax(available.get(k) || zeroTax(), v)));

  const findings: AdvanceFinding[] = [];

  available.forEach((openAmt, key) => {
    const k = parseKey(key);
    const label = describeKey(k);
    const openTaxable = openAmt.taxable;
    if (openTaxable <= threshold) return;

    const invoiceTaxable = invoices.get(key) || 0;
    const reported = (draftTxpd.get(key) || zeroTax()).taxable;

    // Rule 3 — adjusting more advance than exists. Reported first because it
    // is a SHORT payment, the more dangerous direction.
    if (reported - openTaxable > threshold) {
      findings.push({
        code: 'OVER_ADJUSTED',
        severity: 'hard',
        key, keyLabel: label,
        title: 'Table 11B adjusts more advance than is open',
        detail:
          `${label}: this return adjusts ${inr(reported)} against an open advance of only ` +
          `${inr(openTaxable)}. Over-adjusting reverses tax that was never paid — this is a short ` +
          'payment, not an overpayment.',
        amountAtRisk: reported - openTaxable,
      });
      return;
    }

    if (invoiceTaxable <= 0) {
      // Rule 5 — an advance is open but nothing was billed against it here.
      findings.push({
        code: 'OPEN_NO_INVOICE',
        severity: 'soft',
        key, keyLabel: label,
        title: 'Open advance carried forward',
        detail:
          `${label}: ${inr(openTaxable)} of advance remains open, and this return has no invoice at ` +
          'the same place of supply and rate. Nothing to set off this month — carried forward.',
        amountAtRisk: openTaxable,
      });
      return;
    }

    const suggested = Math.min(openTaxable, invoiceTaxable);
    const shortfall = suggested - reported;
    if (shortfall <= threshold) return;

    const suggestion = {
      taxable: suggested,
      ratePct: k.ratePct,
      pos: k.pos,
      splyTy: k.splyTy,
      tax: taxFor(suggested, k.ratePct, k.splyTy),
    };

    if (reported <= 0) {
      // Rule 1 — the failure this module exists to prevent.
      findings.push({
        code: 'NO_SETOFF_REPORTED',
        severity: 'hard',
        key, keyLabel: label,
        title: 'Advance not set off against this month’s invoices',
        detail:
          `${label}: ${inr(openTaxable)} of advance is open and this return bills ${inr(invoiceTaxable)} ` +
          'at the same place of supply and rate, but Table 11B is empty. Filing as-is pays tax twice on ' +
          `the same consideration — ${inr(totalTax(suggestion.tax))} of it.`,
        suggested: suggestion,
        amountAtRisk: suggested,
      });
      return;
    }

    // Rule 2 — partial set-off. Proportional guard as well as the rupee one,
    // so a large advance with a small deliberate residue doesn't block.
    if (shortfall / suggested > SHORTFALL_PCT_TRIGGER) {
      findings.push({
        code: 'SETOFF_SHORT',
        severity: 'hard',
        key, keyLabel: label,
        title: 'Table 11B set-off is short of the invoices raised',
        detail:
          `${label}: this return adjusts ${inr(reported)} but ${inr(suggested)} of advance is covered by ` +
          `invoices raised this month — ${inr(shortfall)} short.`,
        suggested: suggestion,
        amountAtRisk: shortfall,
      });
    }
  });

  // Rule 6 — stale advances. One finding for the whole client, not per key:
  // a list of six aged keys is noise, the fact that money has been sitting is
  // the signal.
  if (ledger.oldestOpenPeriod && ledger.closingTotal.taxable > threshold) {
    const age = periodOrdinal(input.periodMonth) - periodOrdinal(ledger.oldestOpenPeriod);
    if (Number.isFinite(age) && age >= STALE_ADVANCE_MONTHS) {
      findings.push({
        code: 'STALE_ADVANCE',
        severity: 'soft',
        title: `Advance open for ${age} months`,
        detail:
          `${inr(ledger.closingTotal.taxable)} of advance has been open since ${ledger.oldestOpenPeriod}. ` +
          'Worth confirming it is still a live advance and not an invoice that was billed without a set-off.',
        amountAtRisk: ledger.closingTotal.taxable,
      });
    }
  }

  // Rule 4 — an amendment restating a period that is already Filed needs its
  // differential in this period's 3B, or the GSTR-1 side of the correction has
  // been made and the 3B side has not (§7.3).
  const amendedPeriods = new Set<string>();
  [...(draft.ata || []), ...(draft.txpda || [])].forEach((g: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
    const p = fpToMmYyyy(g?.omon);
    if (p) amendedPeriods.add(p);
  });
  if (amendedPeriods.size > 0) {
    const [filedRes, adjRes] = await Promise.all([
      supabase.from('filing_status').select('period_month, status, return_type')
        .eq('client_id', input.clientId).in('period_month', Array.from(amendedPeriods)),
      supabase.from('gstr3b_adjustments').select('table_ref, source')
        .eq('client_id', input.clientId).eq('period_month', input.periodMonth),
    ]);
    const filedAmended = ((filedRes.data as any[]) || []) // eslint-disable-line @typescript-eslint/no-explicit-any
      .filter((r) => String(r.status || '') === 'Filed')
      .map((r) => String(r.period_month));
    const hasPriorPeriodAdj = ((adjRes.data as any[]) || []) // eslint-disable-line @typescript-eslint/no-explicit-any
      .some((r) => String(r.table_ref) === '3.1(a)' && String(r.source) === 'Prior Period');
    if (filedAmended.length > 0 && !hasPriorPeriodAdj) {
      const periods = Array.from(new Set(filedAmended)).sort((a, b) => periodOrdinal(a) - periodOrdinal(b));
      findings.push({
        code: 'AMENDMENT_UNRECONCILED',
        severity: 'hard',
        title: 'Table 11(2) amendment has no matching GSTR-3B adjustment',
        detail:
          `This return amends ${periods.join(', ')}, already filed. An amendment restates that period's ` +
          'figure, so the differential has to reach this month’s 3B as a GSTR-3B Adjustment against ' +
          '3.1(a) with source "Prior Period" — none is recorded. Without it the GSTR-1 side of the ' +
          'correction is made and the 3B side is not.',
      });
    }
  }

  // Rules 7 and 8 — register-backed clients only. Both are SOFT by design:
  // they mean the working paper and the filed return disagree, which needs a
  // human, but the RETURN is what was filed. The register is a record we keep,
  // not authority to block a filing on.
  const register = await fetchRegister(input.clientId);
  if (register.receipts.length > 0) {
    // 7 — Table 11A reported with no receipt voucher behind it. The register
    // is the document trail for an advance; an 11A entry with nothing behind
    // it cannot be evidenced later.
    const receiptKeysThisPeriod = new Set(
      register.receipts
        .filter((r) => r.period_month === input.periodMonth && r.supply_nature !== 'GOODS')
        .map((r) => keyOf(receiptKey(r))),
    );
    draftAt.forEach((amt, key) => {
      if (amt.taxable <= threshold) return;
      if (receiptKeysThisPeriod.has(key)) return;
      const label = describeKey(parseKey(key));
      findings.push({
        code: 'RECEIPT_NOT_IN_REGISTER',
        severity: 'soft',
        key, keyLabel: label,
        title: 'Table 11A has no receipt voucher in the register',
        detail:
          `${label}: this return reports ${inr(amt.taxable)} of advance received, but no receipt is recorded ` +
          'in the Advance Register for this period. Add it so the advance can be linked to the invoice that ' +
          'later absorbs it.',
        amountAtRisk: amt.taxable,
      });
    });

    // 9 — a refund recorded this period nets against THIS period's Table 11A,
    // not Table 11B (§ refund treatment). Raised as an instruction rather than
    // a detected error: whether the reduction has already been made to the
    // draft is not something the JSON can be asked, so this stays advisory and
    // is worded as an action to confirm.
    planRefundOffsets(register.receipts, register.adjustments, input.periodMonth, new Map(
      Array.from(draftAt.entries()).map(([k, v]) => [k, v.taxable]),
    )).forEach((plan) => {
      if (plan.refundTotal <= threshold) return;
      const label = describeKey(parseKey(plan.key));
      findings.push({
        code: 'REFUND_NEEDS_11A_OFFSET',
        severity: 'soft',
        key: plan.key, keyLabel: label,
        title: 'Refunded advance nets against Table 11A, not 11B',
        detail:
          `${label}: ${inr(plan.refundTotal)} of advance was refunded or written back this period. ` +
          `Reduce Table 11A by ${inr(plan.offsetAmount)} against this month's pool of ` +
          `${inr(plan.availableInPeriod)}` +
          (plan.forfeitedAmount > threshold
            ? `; ${inr(plan.forfeitedAmount)} exceeds the pool and is forfeited — the portal rejects a negative Table 11A. Recover it by credit note under s.34 if that route is open.`
            : '.') +
          ' It does not belong in Table 11B.',
        amountAtRisk: plan.refundTotal,
      });
    });

    // 8 — the register's own closing disagrees with the filed position.
    const regClosing = registerClosingByKey(register.receipts, register.adjustments, input.periodMonth);
    reconcileRegister(regClosing, ledger.closingByKey, threshold).forEach((row) => {
      findings.push({
        code: 'REGISTER_DIVERGED',
        severity: 'soft',
        key: row.key, keyLabel: row.label,
        title: 'Advance Register does not agree with the filed returns',
        detail:
          `${row.label}: the register shows ${inr(row.register)} open, the returns show ${inr(row.filed)} — ` +
          `a difference of ${inr(Math.abs(row.difference))}. One of the two is missing an entry.`,
        amountAtRisk: Math.abs(row.difference),
      });
    });
  }

  // QRMP: on an optional IFF month every finding drops to advisory. Done here,
  // once, rather than at each rule — a rule that has to remember to check the
  // scheme is a rule that will one day forget.
  const optionalIff = await isOptionalIffPeriod(input.clientId, input.periodMonth, input.registrationType);
  const finalFindings = optionalIff
    ? findings.map((f) => (f.severity === 'hard'
      ? {
        ...f,
        severity: 'soft' as AdvanceSeverity,
        detail: `${f.detail} (Advisory only: this is an optional IFF month under QRMP — Table 11B is reported in the quarter-end GSTR-1, so the set-off cannot be made here.)`,
      }
      : f))
    : findings;

  const findingsOut = finalFindings;
  const hasHard = findingsOut.some((f) => f.severity === 'hard');
  return {
    severity: hasHard ? 'hard' : findingsOut.length > 0 ? 'soft' : 'ok',
    findings: findingsOut,
    fingerprint: fingerprintOf(findingsOut),
    ledger,
    openTotal: ledger.closingTotal,
  };
}

/**
 * Write the suggested Table 11B rows into a draft JSON, returning a new object.
 * Existing txpd rows for the same key are REPLACED by the suggested figure,
 * not added to — the suggestion is the full amount that should be reported.
 */
export function applySuggestedSetoff(draftJson: any, findings: AdvanceFinding[]): any { // eslint-disable-line @typescript-eslint/no-explicit-any
  const suggestions = findings.filter((f) => f.suggested).map((f) => f.suggested!);
  if (suggestions.length === 0) return draftJson;

  const j = { ...(draftJson || {}) };
  // Rebuild txpd as (pos, sply_ty) groups with one item per rate, the same
  // shape assembleGstr1Json emits.
  const existing = new Map<string, { pos: string; splyTy: string; ratePct: number; tax: TaxAmount }>();
  (j.txpd || []).forEach((g: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
    const pos = String(g?.pos || '');
    const splyTy = String(g?.sply_ty || 'INTRA').toUpperCase();
    const itms = Array.isArray(g?.itms) && g.itms.length ? g.itms : [g];
    itms.forEach((it: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
      const ratePct = num(it?.rt);
      existing.set(keyOf({ pos, ratePct, splyTy }), {
        pos, splyTy, ratePct,
        tax: { taxable: num(it?.ad_amt), igst: num(it?.iamt), cgst: num(it?.camt), sgst: num(it?.samt), cess: num(it?.csamt) },
      });
    });
  });

  suggestions.forEach((s) => {
    existing.set(keyOf({ pos: s.pos, ratePct: s.ratePct, splyTy: s.splyTy }), {
      pos: s.pos, splyTy: s.splyTy, ratePct: s.ratePct, tax: s.tax,
    });
  });

  const groups = new Map<string, any>(); // eslint-disable-line @typescript-eslint/no-explicit-any
  existing.forEach((v) => {
    const gk = `${v.pos}__${v.splyTy}`;
    if (!groups.has(gk)) groups.set(gk, { pos: v.pos, sply_ty: v.splyTy, itms: [] });
    groups.get(gk).itms.push({
      rt: v.ratePct, ad_amt: v.tax.taxable, iamt: v.tax.igst, camt: v.tax.cgst, samt: v.tax.sgst, csamt: v.tax.cess,
    });
  });

  j.txpd = Array.from(groups.values());
  return j;
}

// Re-exported so callers touch one module rather than two.
export { buildAdvanceLedger, shortToMmYyyy, subTax };
