// The full report catalog for the Reports Hub — every report from the
// roadmap's Step 1/2/3 batches, in one place. Pulled out of ReportsPage.tsx
// (which had grown into a 900-line file mixing this data with page logic)
// so the page component stays focused on data-fetching/rendering and this
// file stays focused on "what reports exist."
import {
  Pause, Wallet, Percent, ClipboardList, Hash, Users, AlertTriangle, History, Scale, ArrowRightLeft,
  Rows3, BadgeCheck, Building2, ShoppingCart, Receipt, Layers, Repeat, Ship, PackageOpen, Package,
  ArrowLeftRight, RotateCcw, ListChecks, Gauge, IdCard, Link2, Layers3, Bell, BellRing, Banknote, Coins,
  HandCoins, FileWarning, Wallet2, CreditCard, BookOpen, Landmark, PiggyBank, CalendarRange,
  SplitSquareHorizontal, UserSquare2, FileBadge, ReceiptText, FileClock,
  Calculator, AlarmClock, ShieldAlert, PieChart, Undo2,
} from 'lucide-react';
import {
  buildSuspendedClosingAllClients,
  buildCreditClosingAllClients,
  buildSuspendedClosingPerClient,
  buildCreditClosingPerClient,
} from '@/utils/allClientsReports';
import {
  buildGstr1RateWiseReport,
  buildGstr1SummaryReport,
  buildGstr1HsnSummaryReport,
  buildGstr1CustomerWiseReport,
  buildGstr1ErrorLogReport,
  buildGstr1PyInCyReport,
} from '@/utils/gstr1Reports';
import {
  buildGstr3bLiabilityReport,
  buildGstr3bVsGstr1TaxReport,
  buildGstr3bVsGstr1ComparisonReport,
  buildGstr3bVsGstr2bItcReport,
  buildGstr3bVsGstr2aItcReport,
  buildGstr3bAnnualSummaryReport,
  buildGstr3bOffsetSummaryReport,
} from '@/utils/gstr3bReports';
import {
  buildGstr2bRateWiseReport,
  buildGstr2bSupplierWiseReport,
  buildPurchaseRateWiseReport,
  buildGstr2bPyInCyReport,
} from '@/utils/gstr2bReports';
import {
  buildGstr2aRateWiseReport,
  buildGstr2aSupplierWiseReport,
  buildGstr2aPyInCyReport,
} from '@/utils/gstr2aReports';
import {
  buildPanOutputLiabilityReport,
  buildPanLiabilityVsItcClaimedReport,
  buildPanMultipleCompany2A2BReport,
  buildPanNetOutputLiabilityReport,
} from '@/utils/panReports';
import {
  buildViewNoticesAndOrdersReport,
  buildAdditionalNoticesAndOrdersReport,
  buildRefundFiledOnPortalReport,
  buildRefundClaimedFromItcLedgerReport,
  buildRefundClaimedFromCashLedgerReport,
  buildDrc03FiledOnPortalReport,
  buildDrc03VoluntaryCashLedgerReport,
  buildDrc03VoluntaryCreditLedgerReport,
} from '@/utils/noticeRefundDrc03Reports';
import {
  buildCreditLedgerTransactionsReport,
  buildLiabilityLedgerReport,
  buildCashLedgerReport,
} from '@/utils/portalLedgerReports';
import {
  buildCreditAndLiabilityStatementReport,
  buildTaxpayerInformationReport,
  buildRegistrationCertificateReport,
  buildChallanSummaryReport,
  buildTransitionalCreditClaimedReport,
} from '@/utils/extraPortalReports';
import {
  buildLiabilityDeclaredVsPaidReport,
  buildTaxLiabilityAndItcSummaryReport,
  buildTaxLiabilityExclExportRcmReport,
  buildTaxLiabilityRcmReport,
  buildTaxLiabilityExportSezReport,
  buildItcClaimedExclImportGoodsReport,
  buildItcClaimedImportGoodsReport,
  buildRcmLiabilityVsItcReport,
} from '@/utils/taxLiabilityReports';
import {
  buildCreditReversalReclaimStatement,
  buildRcmLedgerPerClient,
  buildFilingStatusReport,
  buildRcmTaxPaidVsItcClaimedAllClients,
  buildItcClaimedVsUtilizedAllClients,
  buildClientMasterReport,
} from '@/utils/extraLedgerReports';
import {
  buildInterestLateFeeCalculatorReport,
  buildInterestLateFeeAllClientsReport,
  buildInterestScrutinyReport,
  buildRule42ShortReversalReport,
  buildRule42ShortReversalAllClientsReport,
} from '@/utils/interestScrutinyReports';
import type { ReportDefinition } from '@/lib/reportRegistry';

export const REPORTS_CATALOG: ReportDefinition[] = [
  {
    key: 'sus-all',
    title: 'Suspended Ledger — All Clients',
    description: 'One row per client showing the suspended ITC closing balance for the selected month.',
    icon: Pause,
    category: 'ledgers',
    status: 'ready',
    needs: 'month',
    build: ({ month }) => buildSuspendedClosingAllClients(month),
  },
  {
    key: 'cred-all',
    title: 'Credit Ledger — All Clients',
    description: 'One row per client showing the GST Receivable (Credit Ledger) closing balance for the selected month, plus any cash GST payable.',
    icon: Wallet,
    category: 'ledgers',
    status: 'ready',
    needs: 'month',
    build: ({ month }) => buildCreditClosingAllClients(month),
  },
  {
    key: 'sus-one',
    title: 'Suspended Ledger — One Client × All Months',
    description: 'For the picked client, suspended ITC closing balance per month across the financial year of the selected month.',
    icon: Pause,
    category: 'ledgers',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildSuspendedClosingPerClient(clientId!, month),
  },
  {
    key: 'cred-one',
    title: 'Credit Ledger — One Client × All Months',
    description: 'For the picked client, Credit Ledger closing balance per month across the financial year of the selected month, plus cash GST payable.',
    icon: Wallet,
    category: 'ledgers',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildCreditClosingPerClient(clientId!, month),
  },
  {
    key: 'gstr1-rate-wise',
    title: 'GSTR 1 Rate Wise Report',
    description: 'Outward supplies for the selected client and period broken down by tax rate, with a Nil-rated/exempt row and grand total.',
    icon: Percent,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1RateWiseReport(clientId!, month),
  },
  {
    key: 'gstr1-summary',
    title: 'GSTR 1 Summary Report',
    description: 'The portal-style table-wise consolidated summary (4A, 4B, 5, 6A-C, 7, 8, 9B, 10, 11A-B, 12, 13) for the selected client and period.',
    icon: ClipboardList,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1SummaryReport(clientId!, month),
  },
  {
    key: 'gstr1-hsn-summary',
    title: 'GSTR 1 HSN Summary Report',
    description: 'Table 12 HSN-wise summary of outward supplies for the selected client and period, sorted by HSN/SAC code.',
    icon: Hash,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1HsnSummaryReport(clientId!, month),
  },
  {
    key: 'gstr1-customer-wise',
    title: 'GSTR 1 Customer Wise Report',
    description: 'B2B outward supplies (net of credit/debit notes) grouped by registered customer GSTIN for the selected client and period.',
    icon: Users,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1CustomerWiseReport(clientId!, month),
  },
  {
    key: 'gstr1-error-log',
    title: 'GSTR 1 Error Log',
    description: 'Every upload attempt for the selected client and period with its per-invoice portal validation errors, oldest first.',
    icon: AlertTriangle,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1ErrorLogReport(clientId!, month),
  },
  {
    key: 'gstr1-py-in-cy',
    title: 'GSTR 1 (P.Y invoice showing in C.Y)',
    description: 'Flags invoices, credit notes and debit notes dated in an earlier financial year but reported in the selected period\'s GSTR-1.',
    icon: History,
    category: 'gstr1',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr1PyInCyReport(clientId!, month),
  },
  {
    key: 'gstr3b-liability',
    title: 'GSTR 3B Liability Report',
    description: "This app's computed draft GSTR-3B — Table 3.1 outward/RCM liability and Table 4 ITC available/reversed/net — for the selected client and period.",
    icon: Scale,
    category: 'gstr3b',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bLiabilityReport(clientId!, month),
  },
  {
    key: 'gstr3b-vs-gstr1-tax',
    title: 'GSTR 3B vs GSTR 1 Tax Report',
    description: 'Side-by-side tax total from GSTR-1 vs this app\'s computed GSTR-3B Table 3.1, with a variance column. Approximate — see the report for what a variance means.',
    icon: ArrowRightLeft,
    category: 'gstr3b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bVsGstr1TaxReport(clientId!, month),
  },
  {
    key: 'gstr3b-vs-gstr1-comparison',
    title: 'GSTR 3B vs GSTR 1 Comparison Report',
    description: 'Every GSTR-1 table alongside the GSTR-3B Table 3.1 row it feeds, so a mismatch traces to its source section. Approximate — this app\'s draft only, not the as-filed return.',
    icon: Rows3,
    category: 'gstr3b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bVsGstr1ComparisonReport(clientId!, month),
  },
  {
    key: 'gstr3b-vs-gstr2b-itc',
    title: 'GSTR 3B vs GSTR 2B ITC Report',
    description: 'Eligible ITC per Import 2B vs GSTR-3B Table 4(A) ITC Available, with a variance column — catches a stale ITC Summary save. Approximate.',
    icon: BadgeCheck,
    category: 'gstr3b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bVsGstr2bItcReport(clientId!, month),
  },
  {
    key: 'gstr3b-vs-gstr2a-itc',
    title: 'GSTR 3B vs GSTR 2A ITC Report',
    description: 'Every non-RCM document in the imported GSTR-2A vs GSTR-3B Table 4(A) ITC Available, with a variance column. Needs GSTR-2A imported first.',
    icon: BadgeCheck,
    category: 'gstr3b',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bVsGstr2aItcReport(clientId!, month),
  },
  {
    key: 'gstr3b-annual-summary',
    title: 'GSTR 3B Annual Summary Report',
    description: "For the picked client, this app's computed draft GSTR-3B for every month across the financial year, with an annual total.",
    icon: CalendarRange,
    category: 'gstr3b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bAnnualSummaryReport(clientId!, month),
  },
  {
    key: 'gstr3b-offset-summary',
    title: 'GSTR 3B Offset Summary',
    description: 'This app\'s computed indicative ITC-vs-cash offset for the period, following the standard Rule 88A cross-utilization order.',
    icon: SplitSquareHorizontal,
    category: 'gstr3b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr3bOffsetSummaryReport(clientId!, month),
  },
  {
    key: 'gstr2b-rate-wise',
    title: 'GSTR 2B Rate Wise Report',
    description: 'Imported GSTR-2B documents broken down by tax rate (derived from tax ÷ taxable value) for the selected client and period.',
    icon: Percent,
    category: 'gstr2a2b',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2bRateWiseReport(clientId!, month),
  },
  {
    key: 'gstr2b-supplier-wise',
    title: 'GSTR 2B Supplier Wise Report',
    description: 'Imported GSTR-2B documents grouped by supplier GSTIN, sorted by taxable value, for the selected client and period.',
    icon: Building2,
    category: 'gstr2a2b',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2bSupplierWiseReport(clientId!, month),
  },
  {
    key: 'purchase-rate-wise',
    title: 'Purchase Rate Wise Report',
    description: "The client's own books register (not GSTR-2B) broken down by tax rate for the selected client and period.",
    icon: ShoppingCart,
    category: 'gstr2a2b',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildPurchaseRateWiseReport(clientId!, month),
  },
  {
    key: 'gstr2b-py-in-cy',
    title: 'GSTR 2B (P.Y Invoices showing in C.Y)',
    description: 'Flags imported GSTR-2B documents dated in an earlier financial year than the selected return period.',
    icon: History,
    category: 'gstr2a2b',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2bPyInCyReport(clientId!, month),
  },
  {
    key: 'liability-declared-vs-paid',
    title: 'Difference in Liability Declared and Paid',
    description: 'Total output liability (before ITC set-off) vs the indicative net payable after set-off, by tax head, for the selected client and period.',
    icon: Receipt,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildLiabilityDeclaredVsPaidReport(clientId!, month),
  },
  {
    key: 'tax-liability-itc-summary',
    title: 'Tax Liability and ITC Summary',
    description: "A one-page digest of this app's computed draft GSTR-3B — outward, RCM and total liability alongside ITC available, reversed, net and payable.",
    icon: Layers,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildTaxLiabilityAndItcSummaryReport(clientId!, month),
  },
  {
    key: 'tax-liability-excl-export-rcm',
    title: 'Tax Liability Other Than Export/Reverse Charge',
    description: 'Domestic taxable supplies (B2B, B2CL, B2CS, net of notes) by rate — excludes exports/SEZ and Nil-rated/Exempt.',
    icon: Percent,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildTaxLiabilityExclExportRcmReport(clientId!, month),
  },
  {
    key: 'tax-liability-rcm',
    title: 'Tax Liability Due to Reverse Charge',
    description: 'RCM liability from RCM Summary broken down by rate and head (IGST vs CGST+SGST), plus Builder TDR/FSI reverse charge where applicable.',
    icon: Repeat,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildTaxLiabilityRcmReport(clientId!, month),
  },
  {
    key: 'tax-liability-export-sez',
    title: 'Tax Liability Due to Export and SEZ Supplies',
    description: 'GSTR-1 Tables 6A (Exports), 6B (SEZ) and 6C (Deemed Exports) for the selected client and period.',
    icon: Ship,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildTaxLiabilityExportSezReport(clientId!, month),
  },
  {
    key: 'itc-claimed-excl-import-goods',
    title: 'ITC Claimed and Due (Other Than Import of Goods)',
    description: 'GSTR-3B Table 4(A) rows (2)-(5) — import of services, RCM ITC, ISD, and all other ITC.',
    icon: PackageOpen,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildItcClaimedExclImportGoodsReport(clientId!, month),
  },
  {
    key: 'itc-claimed-import-goods',
    title: 'ITC Claimed and Due (Import of Goods)',
    description: 'GSTR-3B Table 4(A)(1) — import of goods, entered directly in ITC Summary.',
    icon: Package,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildItcClaimedImportGoodsReport(clientId!, month),
  },
  {
    key: 'rcm-liability-vs-itc',
    title: 'Reverse Charge Liability Declared and ITC Claimed Thereon',
    description: 'Table 3.1(d) RCM liability vs Table 4(A)(3) RCM ITC claimed — a variance points to a manual GSTR-3B adjustment on one side but not the other.',
    icon: ArrowLeftRight,
    category: 'tax-liability',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildRcmLiabilityVsItcReport(clientId!, month),
  },
  {
    key: 'credit-reversal-reclaim-statement',
    title: 'Credit Reversal and Reclaim Statement',
    description: 'For the picked client, month-by-month suspended-ITC movement across the financial year: reversed, reclaimed, expensed out, and still-suspended closing balance.',
    icon: RotateCcw,
    category: 'ledgers',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildCreditReversalReclaimStatement(clientId!, month),
  },
  {
    key: 'rcm-liability-itc-ledger',
    title: 'RCM Liability/ITC',
    description: 'For the picked client, RCM liability by month across the financial year, from RCM Summary.',
    icon: Repeat,
    category: 'ledgers',
    status: 'ready',
    needs: 'client+month',
    build: ({ clientId, month }) => buildRcmLedgerPerClient(clientId!, month),
  },
  {
    key: 'filing-status-report',
    title: 'Filing Status Report',
    description: 'Every client and return type for the selected month, with status and filed date — one row per client per return.',
    icon: ListChecks,
    category: 'extra',
    status: 'ready',
    needs: 'month',
    build: ({ month }) => buildFilingStatusReport(month),
  },
  {
    key: 'rcm-tax-paid-vs-itc-claimed-all',
    title: 'Tax Paid under RCM vs ITC Claimed',
    description: 'All clients for the selected month: RCM tax paid (Table 3.1d) vs RCM ITC claimed (Table 4A(3)), from this app\'s computed draft GSTR-3B.',
    icon: ArrowLeftRight,
    category: 'extra',
    status: 'ready',
    needs: 'month',
    build: ({ month }) => buildRcmTaxPaidVsItcClaimedAllClients(month),
  },
  {
    key: 'itc-claimed-vs-utilized-all',
    title: 'ITC Claimed vs ITC Utilized',
    description: 'All clients for the selected month: ITC claimed (Table 4A gross) vs ITC actually utilized against this month\'s liability.',
    icon: Gauge,
    category: 'extra',
    status: 'ready',
    needs: 'month',
    build: ({ month }) => buildItcClaimedVsUtilizedAllClients(month),
  },
  {
    key: 'client-master',
    title: 'Client Master',
    description: 'Every client with registration type, sub type, registration date, contact details and assigned accountant — no period needed.',
    icon: IdCard,
    category: 'extra',
    status: 'ready',
    needs: 'none',
    build: () => buildClientMasterReport(),
  },
  {
    key: 'gstr2a-rate-wise',
    title: 'GSTR 2A Rate Wise Report',
    description: 'Imported GSTR-2A documents broken down by tax rate (derived from tax ÷ taxable value). Pull it first from Import 2B\'s GSTR-2A Import card.',
    icon: Percent,
    category: 'gstr2a2b',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2aRateWiseReport(clientId!, month),
  },
  {
    key: 'gstr2a-supplier-wise',
    title: 'GSTR 2A Supplier Wise Report',
    description: 'Imported GSTR-2A documents grouped by supplier GSTIN, sorted by taxable value.',
    icon: Building2,
    category: 'gstr2a2b',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2aSupplierWiseReport(clientId!, month),
  },
  {
    key: 'gstr2a-py-in-cy',
    title: 'GSTR 2A (P.Y Invoices showing in C.Y)',
    description: 'Flags imported GSTR-2A documents dated in an earlier financial year than the selected return period.',
    icon: History,
    category: 'gstr2a2b',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildGstr2aPyInCyReport(clientId!, month),
  },
  {
    key: 'pan-multiple-company-2a2b',
    title: 'GSTR 2A/2B Multiple Company Report',
    description: 'Pick any GSTIN under a PAN — rolls up every client sharing that PAN\'s imported GSTR-2A and GSTR-2B totals, side by side.',
    icon: Layers3,
    category: 'gstr2a2b',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildPanMultipleCompany2A2BReport(clientId!, month),
  },
  {
    key: 'view-notices-and-orders',
    title: 'View Notice and Orders',
    description: 'Every notice/order on record for the client, most recent first. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: Bell,
    category: 'notice',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildViewNoticesAndOrdersReport(clientId!),
  },
  {
    key: 'additional-notices-and-orders',
    title: 'Additional Notices and Orders',
    description: 'The portal\'s separate "Additional Notices and Orders" list. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: BellRing,
    category: 'notice',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildAdditionalNoticesAndOrdersReport(clientId!),
  },
  {
    key: 'refund-filed-on-portal',
    title: 'Refund Filed On Portal',
    description: 'Every refund application on record for the client, most recent first. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: Banknote,
    category: 'refund',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildRefundFiledOnPortalReport(clientId!),
  },
  {
    key: 'refund-claimed-from-itc-ledger',
    title: 'Refund Claimed From ITC Ledger',
    description: 'Refund applications claimed against the Electronic Credit Ledger. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: Coins,
    category: 'refund',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildRefundClaimedFromItcLedgerReport(clientId!),
  },
  {
    key: 'refund-claimed-from-cash-ledger',
    title: 'Refund Claimed From Cash Ledger',
    description: 'Refund applications claimed against the Electronic Cash Ledger. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: HandCoins,
    category: 'refund',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildRefundClaimedFromCashLedgerReport(clientId!),
  },
  {
    key: 'drc03-filed-on-portal',
    title: 'DRC-03 Filed On Portal',
    description: 'Every DRC-03 voluntary payment on record for the client, most recent first. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: FileWarning,
    category: 'drc03',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildDrc03FiledOnPortalReport(clientId!),
  },
  {
    key: 'drc03-voluntary-cash-ledger',
    title: 'Voluntary Payment Of Cash Ledger',
    description: 'DRC-03 payments discharged from the Cash Ledger. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: Wallet2,
    category: 'drc03',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildDrc03VoluntaryCashLedgerReport(clientId!),
  },
  {
    key: 'drc03-voluntary-credit-ledger',
    title: 'Voluntary Payment Of Credit Ledger',
    description: 'DRC-03 payments discharged from the Credit Ledger. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: CreditCard,
    category: 'drc03',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildDrc03VoluntaryCreditLedgerReport(clientId!),
  },
  {
    key: 'credit-ledger-transaction-detail',
    title: 'Credit Ledger (Transaction Detail)',
    description: 'Every portal transaction row for the picked client across the financial year — not just the opening balance the other Credit Ledger reports use.',
    icon: BookOpen,
    category: 'ledgers',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildCreditLedgerTransactionsReport(clientId!, month),
  },
  {
    key: 'liability-ledger',
    title: 'Liability Ledger',
    description: 'Electronic Liability Register entries for the picked client across the financial year. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: Landmark,
    category: 'ledgers',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildLiabilityLedgerReport(clientId!, month),
  },
  {
    key: 'cash-ledger',
    title: 'Cash Ledger',
    description: 'Electronic Cash Ledger entries for the picked client across the financial year. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: PiggyBank,
    category: 'ledgers',
    status: 'extends-login',
    needs: 'client+month',
    build: ({ clientId, month }) => buildCashLedgerReport(clientId!, month),
  },
  {
    key: 'credit-and-liability-statement',
    title: 'Credit And Liability Statement',
    description: "For the picked client, month-by-month total liability, ITC set off, cash paid and ITC carried forward across the financial year — this app's computed draft.",
    icon: SplitSquareHorizontal,
    category: 'extra',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildCreditAndLiabilityStatementReport(clientId!, month),
  },
  {
    key: 'taxpayer-information',
    title: 'Taxpayer Information',
    description: "The client's portal registration profile (legal/trade name, constitution, jurisdiction). No automated portal pull yet — see the report's error for how to populate it.",
    icon: UserSquare2,
    category: 'extra',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildTaxpayerInformationReport(clientId!),
  },
  {
    key: 'registration-certificate',
    title: 'Download Registration Certificate',
    description: 'Points to the client\'s Registration Certificate on record. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: FileBadge,
    category: 'extra',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildRegistrationCertificateReport(clientId!),
  },
  {
    key: 'challan-summary',
    title: 'Challan Summary Report',
    description: 'Every challan on record for the client, most recent first. No automated portal pull yet — see the report\'s error for how to populate it.',
    icon: ReceiptText,
    category: 'extra',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildChallanSummaryReport(clientId!),
  },
  {
    key: 'transitional-credit-claimed',
    title: 'Transitional Credit Claimed Report',
    description: 'TRAN-1/TRAN-2 one-time 2017 transitional credit on record. No automated portal pull yet, and it\'s unconfirmed whether the portal still exposes this data.',
    icon: FileClock,
    category: 'extra',
    status: 'extends-login',
    needs: 'client',
    build: ({ clientId }) => buildTransitionalCreditClaimedReport(clientId!),
  },
  {
    key: 'pan-output-liability',
    title: 'Output Liability as per GSTR 1 and GSTR 3B (PAN-Based)',
    description: "Pick any GSTIN under a PAN — rolls up every client sharing that PAN's GSTR-1 output tax vs computed GSTR-3B liability, side by side.",
    icon: Link2,
    category: 'pan',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildPanOutputLiabilityReport(clientId!, month),
  },
  {
    key: 'pan-liability-vs-itc-claimed',
    title: 'Liability as per GSTR 1 and ITC Claimed as per GSTR 3B (PAN-Based)',
    description: "Pick any GSTIN under a PAN — rolls up every client sharing that PAN's GSTR-1 output liability vs GSTR-3B ITC claimed, side by side.",
    icon: Layers3,
    category: 'pan',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildPanLiabilityVsItcClaimedReport(clientId!, month),
  },
  {
    key: 'pan-net-output-liability',
    title: 'Net Output Liability Report (PAN-Based)',
    description: "Pick any GSTIN under a PAN — rolls up every client sharing that PAN's NET indicative payable (after ITC set-off), the group's actual cash-flow exposure.",
    icon: Gauge,
    category: 'pan',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildPanNetOutputLiabilityReport(clientId!, month),
  },
  {
    key: 'interest-late-fee-calculator',
    title: 'Interest and Late Fee Calculator',
    description: 'For the selected client and period — computed interest (Rule 88B, net of ITC) and late fee (s.47) working, with due date, filed date and days late.',
    icon: Calculator,
    category: 'interest',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildInterestLateFeeCalculatorReport(clientId!, month),
  },
  {
    key: 'interest-late-fee-all-clients',
    title: 'Interest and Late Fees Report — All Clients',
    description: 'One row per client with a GSTR-3B filing record for the selected month — computed interest and late fee, side by side.',
    icon: AlarmClock,
    category: 'interest',
    status: 'ready-approx',
    needs: 'month',
    build: ({ month }) => buildInterestLateFeeAllClientsReport(month),
  },
  {
    key: 'interest-scrutiny',
    title: 'Scrutiny of Interest due to Late Payment of 3B',
    description: 'Exceptions only — clients with computed interest greater than zero for the selected month, so late filings surface without scanning the full client list.',
    icon: ShieldAlert,
    category: 'scrutiny',
    status: 'ready-approx',
    needs: 'month',
    build: ({ month }) => buildInterestScrutinyReport(month),
  },
  {
    key: 'rule42-short-reversal',
    title: 'Short Reversal of ITC — Section 17(2) & Rule 42',
    description: "For the selected client and period — the Rule 42 common-credit reversal working (exempt/aggregate turnover ratio) vs what's already declared as reversed, and the shortfall. Rule 42 (inputs) only — Rule 43 (capital goods) out of scope.",
    icon: PieChart,
    category: 'scrutiny',
    status: 'ready-approx',
    needs: 'client+month',
    build: ({ clientId, month }) => buildRule42ShortReversalReport(clientId!, month),
  },
  {
    key: 'rule42-short-reversal-all-clients',
    title: 'Short Reversal of ITC in GSTR-3B',
    description: 'Exceptions only — clients with a computed Rule 42 shortfall greater than zero for the selected month (needs annual turnover on record).',
    icon: Undo2,
    category: 'scrutiny',
    status: 'ready-approx',
    needs: 'month',
    build: ({ month }) => buildRule42ShortReversalAllClientsReport(month),
  },
];
